version: "3.5"
services:
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '127.0.0.1:8025:8025'
  django:
    env_file:
      - envs/tools/mailhog.env
    depends_on:
      - mailhog
  celery-worker:
    env_file:
      - envs/tools/mailhog.env
    depends_on:
      - mailhog
  celery-beat:
    env_file:
      - envs/tools/mailhog.env
    depends_on:
      - mailhog
