"""
Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.envcom/en/2.0/ref/settings/
"""

import os

from talos.env import BASE_DIR, env

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('TALOS_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('TALOS_DEBUG', default=False)

ALLOWED_HOSTS = env.list('TALOS_ALLOWED_HOSTS', default=['*'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions',
    'rest_framework',

    'talos.apps.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'talos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': env.bool('TALOS_TEMPLATES_DEBUG', default=DEBUG),
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'talos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': env.db('TALOS_DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = env.str('TALOS_LANGUAGE_CODE', default='en-us')

TIME_ZONE = env.str('TALOS_TIME_ZONE', default='UTC')

USE_I18N = env.bool('TALOS_USE_I18N', default=True)

USE_L10N = env.bool('TALOS_USE_L10N', default=True)

USE_TZ = env.bool('TALOS_USE_TZ', default=True)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

STATIC_URL = '/s/'
STATIC_ROOT = os.path.join(BASE_DIR, os.path.pardir, 'public', 'static')

MEDIA_URL = '/m/'
MEDIA_ROOT = os.path.join(BASE_DIR, os.path.pardir, 'public', 'media')

# Session
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"
SESSION_COOKIE_NAME = 'talos_sessionid'

# IMPORTANT: It needs because we have a problem with proxing header set-cookie on Nginx (auth_request_set)
CSRF_USE_SESSIONS = True

# Caches
CACHES = {
    'default': env.cache('TALOS_CACHE_URL'),
    'session': env.cache('TALOS_CACHE_SESSION_URL')
}

# Email
EMAIL_BACKEND = env.str('TALOS_EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env.str('TALOS_EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('TALOS_EMAIL_PORT', default=25)
EMAIL_HOST_USER = env.str('TALOS_EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env.str('TALOS_EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('TALOS_EMAIL_USE_TLS', default=False)
EMAIL_SUBJECT_PREFIX = env.str('TALOS_EMAIL_SUBJECT_PREFIX', '[talos]')
DEFAULT_FROM_EMAIL = env.str('TALOS_DEFAULT_FROM_EMAIL')

#
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]
