# Generated by Django 2.0.7 on 2018-08-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
